modLoader="javafml"
loaderVersion="[46,)"
license="LGPL"
issueTrackerURL="https://github.com/Viola-Siemens/Random-Looting/issues"

[[mods]]
modId="randomlooting"
version="${file.jarVersion}"
displayName="Random Looting"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
All loot tables are messed up by this mod. You may be able to get a wheat seed after killing a wither, or get diamonds after breaking oak logs. Can you still beat the game?
'''

[[dependencies.randomlooting]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randomlooting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"